// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TheGuardiansEyesData;

#nullable disable

namespace TheGuardiansEyesData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheGuardiansEyesModel.DesastreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cobrade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DataOcorrencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdGrupoDesastre")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdLocal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Impacto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TerrenoGeograficoModelId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupoDesastre");

                    b.HasIndex("IdLocal");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Impacto");

                    b.HasIndex("TerrenoGeograficoModelId");

                    b.ToTable("Desastres");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.DroneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DistanciaMaxima")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Peso")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TempoVoo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("VelocidadeMaxima")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.GrupoDesastreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeGrupo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("GruposDesastre");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.ImagensCapturadasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DroneModelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Hospedagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdDesastre")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdDrone")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("IdImpactoClassificacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdLocal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DroneModelId");

                    b.HasIndex("IdDesastre");

                    b.HasIndex("IdDrone");

                    b.HasIndex("IdImpactoClassificacao");

                    b.HasIndex("IdLocal");

                    b.ToTable("ImagensCapturadas");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.ImpactoClassificacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescNivel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Nivel")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("ImpactosClassificacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescNivel = "Leve",
                            Nivel = 1
                        },
                        new
                        {
                            Id = 2,
                            DescNivel = "Moderado",
                            Nivel = 2
                        },
                        new
                        {
                            Id = 3,
                            DescNivel = "Grave",
                            Nivel = 3
                        });
                });

            modelBuilder.Entity("TheGuardiansEyesModel.ImpactoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImpactoClassificacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ImpactoClassificacaoId");

                    b.ToTable("Impactos");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.LocalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cep")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Municipio")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Numero")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.SensoresModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chip")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MediaTensaoRegistrada")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Saida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoSaida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Utilidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.SubGrupoDesastreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoDesastreId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SubTipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Subgrupo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoDesastreId");

                    b.ToTable("SubGrupoDesastre");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.TerrenoGeograficoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeTerreno")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TerrenosGeograficos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeTerreno = "Montanha"
                        },
                        new
                        {
                            Id = 2,
                            NomeTerreno = "Planície"
                        },
                        new
                        {
                            Id = 3,
                            NomeTerreno = "Floresta"
                        },
                        new
                        {
                            Id = 4,
                            NomeTerreno = "Área Urbana"
                        },
                        new
                        {
                            Id = 5,
                            NomeTerreno = "Deserto"
                        },
                        new
                        {
                            Id = 6,
                            NomeTerreno = "Pantanal"
                        },
                        new
                        {
                            Id = 7,
                            NomeTerreno = "Litoral"
                        });
                });

            modelBuilder.Entity("TheGuardiansEyesModel.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.DesastreModel", b =>
                {
                    b.HasOne("TheGuardiansEyesModel.GrupoDesastreModel", "GrupoDesastre")
                        .WithMany("Desastres")
                        .HasForeignKey("IdGrupoDesastre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheGuardiansEyesModel.LocalModel", "Local")
                        .WithMany("Desastres")
                        .HasForeignKey("IdLocal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheGuardiansEyesModel.UsuarioModel", "Usuario")
                        .WithMany("Desastres")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheGuardiansEyesModel.ImpactoModel", "ImpactoClassificacao")
                        .WithMany("Desastres")
                        .HasForeignKey("Impacto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheGuardiansEyesModel.TerrenoGeograficoModel", null)
                        .WithMany("Desastres")
                        .HasForeignKey("TerrenoGeograficoModelId");

                    b.Navigation("GrupoDesastre");

                    b.Navigation("ImpactoClassificacao");

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.ImagensCapturadasModel", b =>
                {
                    b.HasOne("TheGuardiansEyesModel.DroneModel", null)
                        .WithMany("ImagensCapturadas")
                        .HasForeignKey("DroneModelId");

                    b.HasOne("TheGuardiansEyesModel.DesastreModel", "Desastre")
                        .WithMany("ImagensCapturadas")
                        .HasForeignKey("IdDesastre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGuardiansEyesModel.DroneModel", "Drone")
                        .WithMany()
                        .HasForeignKey("IdDrone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGuardiansEyesModel.ImpactoClassificacaoModel", "ImpactoClassificacao")
                        .WithMany()
                        .HasForeignKey("IdImpactoClassificacao");

                    b.HasOne("TheGuardiansEyesModel.LocalModel", "Local")
                        .WithMany("ImagensCapturadas")
                        .HasForeignKey("IdLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desastre");

                    b.Navigation("Drone");

                    b.Navigation("ImpactoClassificacao");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.ImpactoModel", b =>
                {
                    b.HasOne("TheGuardiansEyesModel.ImpactoClassificacaoModel", "ImpactoClassificacao")
                        .WithMany()
                        .HasForeignKey("ImpactoClassificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImpactoClassificacao");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.SubGrupoDesastreModel", b =>
                {
                    b.HasOne("TheGuardiansEyesModel.GrupoDesastreModel", "GrupoDesastre")
                        .WithMany("Subgrupos")
                        .HasForeignKey("GrupoDesastreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoDesastre");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.DesastreModel", b =>
                {
                    b.Navigation("ImagensCapturadas");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.DroneModel", b =>
                {
                    b.Navigation("ImagensCapturadas");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.GrupoDesastreModel", b =>
                {
                    b.Navigation("Desastres");

                    b.Navigation("Subgrupos");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.ImpactoModel", b =>
                {
                    b.Navigation("Desastres");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.LocalModel", b =>
                {
                    b.Navigation("Desastres");

                    b.Navigation("ImagensCapturadas");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.TerrenoGeograficoModel", b =>
                {
                    b.Navigation("Desastres");
                });

            modelBuilder.Entity("TheGuardiansEyesModel.UsuarioModel", b =>
                {
                    b.Navigation("Desastres");
                });
#pragma warning restore 612, 618
        }
    }
}
